export const ActionConstants = {
    LOAD_CONFIG_SUCCESS: 'LOAD_CONFIG_SUCCESS',
    LOAD_CONFIG_FAIL: 'LOAD_CONFIG_FAIL',
    LOAD_SLIDER_SUCCESS: 'LOAD_SLIDER_SUCCESS',
    LOAD_SLIDER_FAIL: 'LOAD_SLIDER_FAIL',
    QUESTION_RESPONSE_SUCCESS: 'QUESTION_RESPONSE_SUCCESS',
    QUESTION_RESPONSE_FAIL: 'QUESTION_RESPONSE_FAIL',
    KEEP_TIME_SUCCESS: 'KEEP_TIME_SUCCESS',
    KEEP_TIME_FAIL: 'KEEP_TIME_FAIL',
};