export const ActionConstants = {
    LOAD_CONFIG_SUCCESS: 'LOAD_CONFIG_SUCCESS',
    LOAD_CONFIG_FAIL: 'LOAD_CONFIG_FAIL',
    LOAD_SLIDER_SUCCESS: 'LOAD_SLIDER_SUCCESS',
    LOAD_SLIDER_FAIL: 'LOAD_SLIDER_FAIL',
};